# Created using wingetcreate 1.2.7.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.4.0.schema.json

PackageIdentifier: Neurodesk.NeurodeskApp
PackageVersion: 1.0.0
PackageLocale: en-US
Publisher: University of Queensland
PublisherUrl: https://www.neurodesk.org/
PublisherSupportUrl: https://github.com/orgs/NeuroDesk/discussions
Author: Neurodesk Team
PackageName: NeurodeskApp
PackageUrl: https://github.com/NeuroDesk/neurodesk-app/releases/latest/download/NeurodeskApp-Setup-Windows.exe
License: MIT License
Copyright: Copyright © 2023 Neurodesk
ShortDescription: Neurodesktop application, based on Electron.
Description: Neurodesktop application, based on Electron.
Moniker: neurodesk
Tags:
- neurodesk
- neuroimaging
- image processing
- docker
- singularity
ManifestType: defaultLocale
ManifestVersion: 1.4.0
